SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 1
TRAIN:
  DA_METHOD: PADAN
  MODEL: DeepLabv2_padan
  RESTORE_FROM: ./padan/pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: False
  LAMBDA_ADV_MAIN: 0.001
TEST:
  MODE: best